name: TEKtalk
options: {bundleIdPrefix: vn.tektalk, deploymentTarget: {iOS: "16.0"}}
targets:
  TEKtalk:
    type: application
    platform: iOS
    sources: [TEKtalk]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: vn.tektalk.ios
        SWIFT_VERSION: "5.10"
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsLocalNetworking: true
