#include "pch.h"
#include "MainWindow.xaml.h"
#include "ClientLogic.h"
using namespace winrt;using namespace Microsoft::UI::Xaml;using namespace Microsoft::UI::Xaml::Controls;
namespace winrt::TEKtalk::implementation {
TextBlock MainWindow::Text(hstring const& value,double size,bool bold){TextBlock t;t.Text(value);t.FontSize(size);if(bold)t.FontWeight(Windows::UI::Text::FontWeights::SemiBold());return t;}
MainWindow::MainWindow(){InitializeComponent();root_=Root();ExtendsContentIntoTitleBar(true);AppWindow().Resize({1100,720});ShowAuth();}
void MainWindow::ShowAuth(){root_.Children().Clear();auto shell=Grid();shell.ColumnDefinitions().Append(ColumnDefinition());shell.ColumnDefinitions().Append(ColumnDefinition());shell.ColumnDefinitions().GetAt(0).Width(GridLengthHelper::FromPixels(410));auto hero=StackPanel();hero.Background(Media::SolidColorBrush(Windows::UI::ColorHelper::FromArgb(255,23,105,224)));hero.Padding({48});hero.Spacing(18);auto brand=Text(L"TEKtalk",48,true);brand.Foreground(Media::SolidColorBrush(Windows::UI::Colors::White()));hero.Children().Append(brand);auto subtitle=Text(L"Native messaging for Windows\nPowered by shared Rust Core",20);subtitle.Foreground(Media::SolidColorBrush(Windows::UI::Colors::White()));hero.Children().Append(subtitle);auto core=Text(core_.Available()?L"✓ Rust Core connected":L"Rust Core development fallback",13,true);core.Foreground(Media::SolidColorBrush(Windows::UI::Colors::White()));hero.Children().Append(core);Grid::SetColumn(hero,0);shell.Children().Append(hero);auto form=StackPanel();form.Padding({64});form.Spacing(12);form.MaxWidth(520);form.HorizontalAlignment(HorizontalAlignment::Stretch);form.Children().Append(Text(register_mode_?L"Tạo tài khoản":challenge_.empty()?L"Đăng nhập":L"Xác minh thiết bị",34,true));if(challenge_.empty()){phone_=TextBox();phone_.Header(box_value(L"Số điện thoại E.164"));phone_.Text(L"+84");form.Children().Append(phone_);if(register_mode_){name_=TextBox();name_.Header(box_value(L"Tên hiển thị"));form.Children().Append(name_);}password_=PasswordBox();password_.Header(box_value(L"Mật khẩu"));form.Children().Append(password_);if(register_mode_){question_=TextBox();question_.Header(box_value(L"Câu hỏi bảo mật"));question_.Text(L"Tên trường tiểu học của bạn?");form.Children().Append(question_);}}answer_=TextBox();answer_.Header(box_value(challenge_.empty()?L"Câu trả lời bảo mật":L"Trả lời câu hỏi bảo mật"));if(register_mode_||!challenge_.empty())form.Children().Append(answer_);status_=Text(L"");form.Children().Append(status_);auto submit=Button();submit.Content(box_value(challenge_.empty()?(register_mode_?L"Đăng ký":L"Đăng nhập"):L"Xác minh"));submit.HorizontalAlignment(HorizontalAlignment::Stretch);submit.Click([this](auto&&,auto&&){SubmitAuth();});form.Children().Append(submit);if(challenge_.empty()){auto toggle=Button();toggle.Content(box_value(register_mode_?L"Đã có tài khoản? Đăng nhập":L"Chưa có tài khoản? Đăng ký"));toggle.Click([this](auto&&,auto&&){register_mode_=!register_mode_;ShowAuth();});form.Children().Append(toggle);}Grid::SetColumn(form,1);shell.Children().Append(form);root_.Children().Append(shell);}
IAsyncAction MainWindow::SubmitAuth(){try{if(!challenge_.empty()){tokens_=co_await api_.Verify(challenge_,answer_.Text());ShowHost();co_return;}if(!tektalk::ValidE164(phone_.Text().c_str())||!tektalk::ValidPassword(password_.Password().c_str())){status_.Text(L"Kiểm tra số E.164 và mật khẩu mạnh (10 ký tự, chữ hoa, chữ số)");co_return;}if(register_mode_){tokens_=co_await api_.Register(phone_.Text(),name_.Text(),password_.Password(),question_.Text(),answer_.Text());ShowHost();}else{auto result=co_await api_.Login(phone_.Text(),password_.Password());if(result.tokens){tokens_=result.tokens;ShowHost();}else{challenge_=result.challenge_id;ShowAuth();status_.Text(result.question);}}}catch(hresult_error const&e){status_.Text(e.message());}}
void MainWindow::ShowHost(){root_.Children().Clear();auto nav=NavigationView();nav.IsBackButtonVisible(NavigationViewBackButtonVisible::Collapsed);nav.PaneTitle(L"TEKtalk");for(auto const& label:{L"Message",L"AI",L"Me"}){NavigationViewItem item;item.Content(box_value(label));item.Tag(box_value(label));nav.MenuItems().Append(item);}nav.SelectionChanged([this](auto const&,NavigationViewSelectionChangedEventArgs const&e){auto item=e.SelectedItem().try_as<NavigationViewItem>();if(!item)return;auto tag=unbox_value<hstring>(item.Tag());if(tag==L"Message")ShowMessage();else if(tag==L"AI")ShowAI();else ShowMe();});root_.Children().Append(nav);nav.SelectedItem(nav.MenuItems().GetAt(0));}
void MainWindow::ShowMessage(){auto nav=root_.Children().GetAt(0).as<NavigationView>();auto panel=StackPanel();panel.Padding({28});panel.Spacing(10);panel.Children().Append(Text(L"Tin nhắn",32,true));conversation_=TextBox();conversation_.Header(box_value(L"Conversation UUID"));recipient_=TextBox();recipient_.Header(box_value(L"Recipient UUID"));panel.Children().Append(conversation_);panel.Children().Append(recipient_);auto sync=Button();sync.Content(box_value(L"Đồng bộ lịch sử"));sync.Click([this](auto&&,auto&&){LoadMessages();});panel.Children().Append(sync);status_=Text(L"Nhập conversation và recipient UUID");panel.Children().Append(status_);messages_=ListView();messages_.Height(310);panel.Children().Append(messages_);auto row=StackPanel();row.Orientation(Orientation::Horizontal);row.Spacing(8);draft_=TextBox();draft_.PlaceholderText(L"Tin nhắn");draft_.Width(500);row.Children().Append(draft_);auto send=Button();send.Content(box_value(L"Gửi"));send.Click([this](auto&&,auto&&){SendMessage();});row.Children().Append(send);panel.Children().Append(row);nav.Content(panel);}
IAsyncAction MainWindow::LoadMessages(){if(!tokens_||!tektalk::LooksLikeUuid(conversation_.Text().c_str())){status_.Text(L"Conversation UUID không hợp lệ");co_return;}try{auto list=co_await api_.History(tokens_->access_token,conversation_.Text());messages_.Items().Clear();for(auto const&m:list)messages_.Items().Append(box_value(m.body));status_.Text(L"Đã đồng bộ "+to_hstring(list.size())+L" tin");}catch(hresult_error const&e){status_.Text(e.message());}}
IAsyncAction MainWindow::SendMessage(){if(!tokens_||!tektalk::LooksLikeUuid(conversation_.Text().c_str())||!tektalk::LooksLikeUuid(recipient_.Text().c_str())||draft_.Text().empty()){status_.Text(L"Kiểm tra conversation, recipient và nội dung");co_return;}try{auto m=co_await api_.Send(tokens_->access_token,conversation_.Text(),recipient_.Text(),draft_.Text());messages_.Items().Append(box_value(m.body));draft_.Text(L"");status_.Text(L"Đã gửi • Snowflake "+to_hstring(m.id));}catch(hresult_error const&e){status_.Text(e.message());}}
void MainWindow::ShowAI(){auto nav=root_.Children().GetAt(0).as<NavigationView>();auto panel=StackPanel();panel.Padding({42});panel.Spacing(12);panel.Children().Append(Text(L"TEK AI",32,true));panel.Children().Append(Text(L"AI plugin contract đã sẵn sàng. Orchestrator sẽ được nối ở milestone tiếp theo.",16));nav.Content(panel);}
void MainWindow::ShowMe(){auto nav=root_.Children().GetAt(0).as<NavigationView>();auto panel=StackPanel();panel.Padding({42});panel.Spacing(12);panel.Children().Append(Text(L"Me",32,true));if(tokens_){panel.Children().Append(Text(L"User: "+tokens_->user_id));panel.Children().Append(Text(L"Device: "+tokens_->device_id));}panel.Children().Append(Text(core_.Available()?L"Rust Core: Connected":L"Rust Core: Fallback"));auto logout=Button();logout.Content(box_value(L"Đăng xuất"));logout.Click([this](auto&&,auto&&){tokens_.reset();challenge_=L"";ShowAuth();});panel.Children().Append(logout);nav.Content(panel);}
}
