const translations={vi:{connecting:'Đang kết nối',messages:'Tin nhắn',me:'Cá nhân',inbox:'HỘP THƯ',search:'Tìm kiếm',welcomeShort:'Chào mừng bạn đến TEKtalk',teamMessage:'Bản demo Web đã sẵn sàng ✨',designMessage:'Đã gửi một ảnh',yesterday:'Hôm qua',online:'Đang hoạt động',today:'Hôm nay',welcome:'Xin chào! Đây là TEKtalk Web — cùng một hợp đồng API và mô hình dữ liệu với các ứng dụng native.',tryMessage:'Bạn có thể đăng nhập backend local hoặc bật chế độ demo để trải nghiệm ngay.',typeMessage:'Nhập tin nhắn',aiTitle:'Trợ lý cho mọi cuộc trò chuyện',aiBody:'Tóm tắt hội thoại, soạn câu trả lời và tìm thông tin trong một không gian riêng tư.',summarize:'Tóm tắt cuộc trò chuyện',draft:'Soạn câu trả lời thân thiện',tasks:'Tìm các việc cần làm',account:'Tài khoản',signInHint:'Đăng nhập để đồng bộ tin nhắn',appearance:'Giao diện',systemTheme:'Sáng, tối và theo hệ thống',privacy:'Quyền riêng tư',privacyHint:'Session và thiết bị',welcomeBack:'Chào mừng đến TEKtalk',authIntro:'Kết nối với backend local hoặc dùng dữ liệu demo.',login:'Đăng nhập',register:'Đăng ký',phone:'Số điện thoại',displayName:'Tên hiển thị',password:'Mật khẩu',securityQuestion:'Câu hỏi bảo mật',securityAnswer:'Câu trả lời',continue:'Tiếp tục',demoMode:'Trải nghiệm chế độ demo'},en:{connecting:'Connecting',messages:'Messages',me:'Me',inbox:'INBOX',search:'Search',welcomeShort:'Welcome to TEKtalk',teamMessage:'The Web demo is ready ✨',designMessage:'Sent a photo',yesterday:'Yesterday',online:'Online',today:'Today',welcome:'Hello! This is TEKtalk Web — using the same API contract and data model as the native applications.',tryMessage:'Sign in to your local backend or enable demo mode to explore instantly.',typeMessage:'Type a message',aiTitle:'An assistant for every conversation',aiBody:'Summarize conversations, draft replies, and find information in a private workspace.',summarize:'Summarize conversation',draft:'Draft a friendly reply',tasks:'Find action items',account:'Account',signInHint:'Sign in to sync messages',appearance:'Appearance',systemTheme:'Light, dark, and system',privacy:'Privacy',privacyHint:'Sessions and devices',welcomeBack:'Welcome to TEKtalk',authIntro:'Connect to the local backend or use demo data.',login:'Sign in',register:'Create account',phone:'Phone number',displayName:'Display name',password:'Password',securityQuestion:'Security question',securityAnswer:'Security answer',continue:'Continue',demoMode:'Explore demo mode'}};
const state={locale:localStorage.getItem('tektalk.locale')||'vi',theme:localStorage.getItem('tektalk.theme')||'light',mode:'login',challengeId:null,tokens:JSON.parse(sessionStorage.getItem('tektalk.tokens')||'null'),demo:sessionStorage.getItem('tektalk.demo')==='1'};
const queryApi=new URLSearchParams(location.search).get('api');
const apiBase=(queryApi||localStorage.getItem('tektalk.api')||(location.port==='5173'?'http://localhost:8080':location.origin)).replace(/\/$/,'');
const $=selector=>document.querySelector(selector); const $$=selector=>[...document.querySelectorAll(selector)];
function translate(){document.documentElement.lang=state.locale;$$('[data-i18n]').forEach(e=>e.textContent=translations[state.locale][e.dataset.i18n]||e.dataset.i18n);$$('[data-i18n-placeholder]').forEach(e=>e.placeholder=translations[state.locale][e.dataset.i18nPlaceholder]||'');$('#languageButton').textContent=state.locale.toUpperCase()}
function setTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;localStorage.setItem('tektalk.theme',theme)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function setConnection(ok){const el=$('#connection');el.classList.toggle('online',ok);el.querySelector('span').textContent=ok?(state.locale==='vi'?'Backend sẵn sàng':'Backend ready'):translations[state.locale].connecting}
async function request(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(state.tokens?.access_token)headers.authorization=`Bearer ${state.tokens.access_token}`;const response=await fetch(`${apiBase}${path}`,{...options,headers});if(!response.ok){let detail;try{detail=await response.json()}catch{detail={}}throw new Error(detail.message||detail.error||`HTTP ${response.status}`)}return response.status===204?null:response.json()}
async function health(){try{const response=await fetch(`${apiBase}/healthz`);setConnection(response.ok)}catch{setConnection(false)}}
function activateTab(name){$$('.nav-item').forEach(e=>e.classList.toggle('active',e.dataset.tab===name));$$('.tab-panel').forEach(e=>e.classList.toggle('active',e.id===name));history.replaceState(null,'',`#${name}`)}
function setAuthMode(mode){state.mode=mode;state.challengeId=null;$$('[data-auth-mode]').forEach(e=>e.classList.toggle('active',e.dataset.authMode===mode));const register=mode==='register';$('#displayNameField').hidden=!register;$('#questionField').hidden=!register;$('#answerField').hidden=!register;$('#challengeField').hidden=true;$('#authError').textContent=''}
function storeTokens(tokens){state.tokens=tokens;state.demo=false;sessionStorage.setItem('tektalk.tokens',JSON.stringify(tokens));sessionStorage.removeItem('tektalk.demo');$('#profileId').textContent=tokens.user_id;$('#authHint').textContent=state.locale==='vi'?'Đã kết nối backend':'Connected to backend';$('#authDialog').close();toast(state.locale==='vi'?'Đăng nhập thành công':'Signed in')}
async function authenticate(event){event.preventDefault();const form=new FormData(event.currentTarget);const error=$('#authError');error.textContent='';try{if(state.challengeId){const tokens=await request('/v1/auth/device/verify',{method:'POST',body:JSON.stringify({challenge_id:state.challengeId,answer:form.get('challenge_answer')})});storeTokens(tokens);return}const common={phone:form.get('phone'),password:form.get('password'),device_name:`TEKtalk Web · ${navigator.platform||'Browser'}`};if(state.mode==='register'){const tokens=await request('/v1/auth/register',{method:'POST',body:JSON.stringify({...common,display_name:form.get('display_name'),security_question:form.get('security_question'),security_answer:form.get('security_answer')})});$('#profileName').textContent=form.get('display_name');storeTokens(tokens)}else{const result=await request('/v1/auth/login',{method:'POST',body:JSON.stringify(common)});if(result.status==='authenticated')storeTokens(result.tokens);else{state.challengeId=result.challenge_id;$('#challengeQuestion').textContent=result.question;$('#challengeField').hidden=false;$('#authSubmit').textContent=state.locale==='vi'?'Xác minh thiết bị':'Verify device'}}}catch(e){error.textContent=e.message}}
function enableDemo(){state.demo=true;sessionStorage.setItem('tektalk.demo','1');$('#profileName').textContent='TEKtalk Explorer';$('#profileId').textContent='Demo workspace';$('#authDialog').close();setConnection(true);toast(state.locale==='vi'?'Đã bật chế độ demo':'Demo mode enabled')}
function appendMessage(text,kind='outgoing',time=new Date()){const item=document.createElement('div');item.className=`message ${kind}`;const p=document.createElement('p');p.textContent=text;const clock=document.createElement('time');clock.textContent=time.toLocaleTimeString(state.locale,{hour:'2-digit',minute:'2-digit'});item.append(p,clock);$('#messageList').append(item);item.scrollIntoView({behavior:'smooth'})}
async function sendMessage(event){event.preventDefault();const input=$('#messageInput');const text=input.value.trim();if(!text)return;appendMessage(text);input.value='';if(state.demo){setTimeout(()=>appendMessage(state.locale==='vi'?'Đã nhận tin nhắn trong chế độ demo. Kết nối backend để đồng bộ đa thiết bị.':'Message received in demo mode. Connect the backend for multi-device sync.','incoming'),450);return}if(!state.tokens){$('#authDialog').showModal();return}const recipient=localStorage.getItem('tektalk.recipient');const conversation=localStorage.getItem('tektalk.conversation');if(!recipient||!conversation){toast(state.locale==='vi'?'Cần cấu hình người nhận để gửi qua backend':'Configure a recipient to send through the backend');return}try{await request('/v1/chat/messages/send',{method:'POST',body:JSON.stringify({conversation_id:conversation,recipient_id:recipient,client_message_id:crypto.randomUUID(),text})})}catch(e){toast(e.message)} }
$$('.nav-item').forEach(button=>button.addEventListener('click',()=>activateTab(button.dataset.tab)));$('#themeButton').addEventListener('click',()=>setTheme(state.theme==='light'?'dark':'light'));$('#profileTheme').addEventListener('click',()=>setTheme(state.theme==='light'?'dark':'light'));$('#languageButton').addEventListener('click',()=>{state.locale=state.locale==='vi'?'en':'vi';localStorage.setItem('tektalk.locale',state.locale);translate();health()});$('#authButton').addEventListener('click',()=>$('#authDialog').showModal());$$('[data-auth-mode]').forEach(button=>button.addEventListener('click',()=>setAuthMode(button.dataset.authMode)));$('#authForm').addEventListener('submit',authenticate);$('#demoButton').addEventListener('click',enableDemo);$('#messageForm').addEventListener('submit',sendMessage);$('#messageInput').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('#messageForm').requestSubmit()}});$$('[data-prompt]').forEach(button=>button.addEventListener('click',()=>{activateTab('messages');appendMessage(button.textContent);setTimeout(()=>appendMessage(state.locale==='vi'?'Tính năng AI đã được mô phỏng trong bản demo Web.':'The AI feature is simulated in the Web demo.','incoming'),350)}));
setTheme(state.theme);translate();activateTab(location.hash.slice(1)||'messages');health();if(!state.tokens&&!state.demo)setTimeout(()=>$('#authDialog').showModal(),500);
